### ISSUE TITLE
lsp-treemacs-error-list returns nothing

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-treemacs#64]
Hello,

If I intentionally introduce some syntax errors in my java source, the language server detects
them instantly and I find them correctly reported in `lsp-ui-flycheck-list` buffer.

However, nothing shows up with `lsp-treemacs-error-list` and no errors seem to occur.

Other `lsp-treemacs` commands, like `lsp-treemacs-symbols`, work well.

My system is `windows 10`, `emacs 27.1` run under `mingw64` with all lsp packages and dependencies updated right now.

**Comment by deb75** [comment]
I still get this issue after having upgraded all lsp packages.

**Comment by yyoncho** [comment]
I think that it is an issue with windows paths. This control is about to be rewritten, so this fix most like will go in when we do that.

**Comment by deb75** [comment]
Yes, it probably has to do with something like this because the same lsp configuration works on my linux and not on windows10.

**Comment by nbfalcon** [comment]
I doesn't work for me either - Ubuntu 20.04 LTS, Emacs 27.1 from source. I will investigate.

**Comment by nbfalcon** [comment]
Nevermind, it broke due to debugging.

**Comment by yyoncho** [comment]
Should be fixed in the latest version.

**Comment by deb75** [comment]
Hi,

Many thanks !

Indeed, it does return a list now, however I am unable to unfold each element of the list, that is to say the unfolded element returns nothing, whereas `lsp-ui-flycheck-list` does return errors

Will try again in order to see  if it is not an error from I

Regards

**Comment by deb75** [comment]
I have updated all `lsp` packages.

I still have this issue : `lsp-treemacs-error-list` does return a list, but I cannot unfold each element of the list by pressing TAB.

Regards
